name: Lint Tutorials And Slides

concurrency:
  group: ci-tutsli-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  lint-frontmatter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: github-pr-review/GITHUB_TOKEN
        run: |
            echo "test.md:1:1:Hi from github-pr-review/GITHUB_TOKEN" | reviewdog -efm="%f:%l:%c:%m" -filter-mode=file -reporter=github-pr-review
        env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: github-pr-review/BLAH
        #run: |
            #echo "test.md:2:2:Hi from github-pr-review/PAT" | reviewdog -efm="%f:%l:%c:%m" -filter-mode=file -reporter=github-pr-review
        #env:
            #REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.BLAH }}

      - name: suggestion
        run: |
            echo '{"message": "test suggestion", "location": {"path": "test.md", "range": {"start": {"line": 9, "column": 1}, "end": {"line": 9, "column": 7}}}, "suggestions": [{"range": {"start": {"line": 9, "column": 3}, "end": {"line": 9, "column": 6}}, "text": "replacement text"}], "severity": "WARNING"}'
            echo "test.md:2:2:Hi from github-pr-review/PAT" | reviewdog -f=rdjson -filter-mode=file -reporter=github-pr-review
        env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
