name: Lint Tutorials And Slides

concurrency:
  group: ci-tutsli-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  lint-frontmatter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      #- name: github-pr-check
        #run: |
          #cat check.txt | reviewdog -efm="%f:%l:%c %m" -filter-mode=file -reporter=github-pr-check
        #env:
            #REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: github-pr-review/GITHUB_TOKEN
        #run: |
          #cat errors.txt | reviewdog -efm="%f:%l:%c %m" -filter-mode=file -reporter=github-pr-review
        #env:
            #REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: github-pr-review/BLAH
        run: |
          cat errors2.txt | reviewdog -efm="%f:%l:%c %m" -filter-mode=file -reporter=github-pr-review
        env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.BLAH }}
