name: Lint Tutorials And Slides

on: [ pull_request_target ]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint-frontmatter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: try review api
        run: |
          curl -X POST \
            -H "Authorization: token ${REVIEWDOG_GITHUB_API_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/hexylena/testing/pulls/2/reviews \
            -d '{"body": "a review", "event": "COMMENT"}'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        run: |
            echo ${{ github.event_name }}
            echo ${{ github.event.pull_request.head.repo.owner }}

      - name: github-pr-review/GITHUB_TOKEN
        run: |
            echo "test.md:1:1:Hi from github-pr-review/GITHUB_TOKEN" | reviewdog -efm="%f:%l:%c:%m" -filter-mode=file -reporter=github-pr-review -tee
        env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
