name: Lint Tutorials And Slides

concurrency:
  group: ci-tutsli-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  lint-frontmatter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: github-pr-review/GITHUB_TOKEN
        run: |
            echo "test.md:1:1:Hi from github-pr-review/GITHUB_TOKEN" | reviewdog -efm="%f:%l:%c:%m" -filter-mode=file -reporter=github-pr-review
        env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: github-pr-review/BLAH
        #run: |
            #echo "test.md:2:2:Hi from github-pr-review/PAT" | reviewdog -efm="%f:%l:%c:%m" -filter-mode=file -reporter=github-pr-review
        #env:
            #REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.BLAH }}

      - name: suggestion
        run: |
            echo "zzzzz" >> test.md
            git diff | reviewdog -f=diff -f.diff.strip=1 -filter-mode=file -reporter=github-pr-review
        env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
